name: Build and Deploy to GitHub Pages
on:
  push:
    branches: main
  
permissions: write-all
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x  
    - name: Update npm
      run: npm install -g npm
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        branch: gh-pages  
        folder: dist  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}